// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: firmachain/nft/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// NftIdListOfOwnerRequest
type NftIdListOfOwnerRequest struct {
	OwnerAddress string             `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	Pagination   *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *NftIdListOfOwnerRequest) Reset()         { *m = NftIdListOfOwnerRequest{} }
func (m *NftIdListOfOwnerRequest) String() string { return proto.CompactTextString(m) }
func (*NftIdListOfOwnerRequest) ProtoMessage()    {}
func (*NftIdListOfOwnerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcc61ddcf845424a, []int{0}
}
func (m *NftIdListOfOwnerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftIdListOfOwnerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftIdListOfOwnerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftIdListOfOwnerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftIdListOfOwnerRequest.Merge(m, src)
}
func (m *NftIdListOfOwnerRequest) XXX_Size() int {
	return m.Size()
}
func (m *NftIdListOfOwnerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NftIdListOfOwnerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NftIdListOfOwnerRequest proto.InternalMessageInfo

func (m *NftIdListOfOwnerRequest) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *NftIdListOfOwnerRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// NftIdListOfOwnerResponse
type NftIdListOfOwnerResponse struct {
	NftIdList  []uint64            `protobuf:"varint,1,rep,packed,name=nft_id_list,json=nftIdList,proto3" json:"nft_id_list,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *NftIdListOfOwnerResponse) Reset()         { *m = NftIdListOfOwnerResponse{} }
func (m *NftIdListOfOwnerResponse) String() string { return proto.CompactTextString(m) }
func (*NftIdListOfOwnerResponse) ProtoMessage()    {}
func (*NftIdListOfOwnerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcc61ddcf845424a, []int{1}
}
func (m *NftIdListOfOwnerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftIdListOfOwnerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftIdListOfOwnerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftIdListOfOwnerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftIdListOfOwnerResponse.Merge(m, src)
}
func (m *NftIdListOfOwnerResponse) XXX_Size() int {
	return m.Size()
}
func (m *NftIdListOfOwnerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NftIdListOfOwnerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NftIdListOfOwnerResponse proto.InternalMessageInfo

func (m *NftIdListOfOwnerResponse) GetNftIdList() []uint64 {
	if m != nil {
		return m.NftIdList
	}
	return nil
}

func (m *NftIdListOfOwnerResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// BalanceOfRequest
type BalanceOfRequest struct {
	OwnerAddress string `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
}

func (m *BalanceOfRequest) Reset()         { *m = BalanceOfRequest{} }
func (m *BalanceOfRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceOfRequest) ProtoMessage()    {}
func (*BalanceOfRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcc61ddcf845424a, []int{2}
}
func (m *BalanceOfRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BalanceOfRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BalanceOfRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BalanceOfRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceOfRequest.Merge(m, src)
}
func (m *BalanceOfRequest) XXX_Size() int {
	return m.Size()
}
func (m *BalanceOfRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceOfRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceOfRequest proto.InternalMessageInfo

func (m *BalanceOfRequest) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

// BalanceOfResponse
type BalanceOfResponse struct {
	Total uint64 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
}

func (m *BalanceOfResponse) Reset()         { *m = BalanceOfResponse{} }
func (m *BalanceOfResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceOfResponse) ProtoMessage()    {}
func (*BalanceOfResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcc61ddcf845424a, []int{3}
}
func (m *BalanceOfResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BalanceOfResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BalanceOfResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BalanceOfResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceOfResponse.Merge(m, src)
}
func (m *BalanceOfResponse) XXX_Size() int {
	return m.Size()
}
func (m *BalanceOfResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceOfResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceOfResponse proto.InternalMessageInfo

func (m *BalanceOfResponse) GetTotal() uint64 {
	if m != nil {
		return m.Total
	}
	return 0
}

// NftItemRequest
type NftItemRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *NftItemRequest) Reset()         { *m = NftItemRequest{} }
func (m *NftItemRequest) String() string { return proto.CompactTextString(m) }
func (*NftItemRequest) ProtoMessage()    {}
func (*NftItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcc61ddcf845424a, []int{4}
}
func (m *NftItemRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftItemRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftItemRequest.Merge(m, src)
}
func (m *NftItemRequest) XXX_Size() int {
	return m.Size()
}
func (m *NftItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NftItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NftItemRequest proto.InternalMessageInfo

func (m *NftItemRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// NftItemResponse
type NftItemResponse struct {
	NftItem *NftItem `protobuf:"bytes,1,opt,name=nft_item,json=nftItem,proto3" json:"nft_item,omitempty"`
}

func (m *NftItemResponse) Reset()         { *m = NftItemResponse{} }
func (m *NftItemResponse) String() string { return proto.CompactTextString(m) }
func (*NftItemResponse) ProtoMessage()    {}
func (*NftItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcc61ddcf845424a, []int{5}
}
func (m *NftItemResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftItemResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftItemResponse.Merge(m, src)
}
func (m *NftItemResponse) XXX_Size() int {
	return m.Size()
}
func (m *NftItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NftItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NftItemResponse proto.InternalMessageInfo

func (m *NftItemResponse) GetNftItem() *NftItem {
	if m != nil {
		return m.NftItem
	}
	return nil
}

// NftItemAllRequest
type NftItemAllRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *NftItemAllRequest) Reset()         { *m = NftItemAllRequest{} }
func (m *NftItemAllRequest) String() string { return proto.CompactTextString(m) }
func (*NftItemAllRequest) ProtoMessage()    {}
func (*NftItemAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcc61ddcf845424a, []int{6}
}
func (m *NftItemAllRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftItemAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftItemAllRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftItemAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftItemAllRequest.Merge(m, src)
}
func (m *NftItemAllRequest) XXX_Size() int {
	return m.Size()
}
func (m *NftItemAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NftItemAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NftItemAllRequest proto.InternalMessageInfo

func (m *NftItemAllRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// NftItemAllResponse
type NftItemAllResponse struct {
	NftItem    []*NftItem          `protobuf:"bytes,1,rep,name=nft_item,json=nftItem,proto3" json:"nft_item,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *NftItemAllResponse) Reset()         { *m = NftItemAllResponse{} }
func (m *NftItemAllResponse) String() string { return proto.CompactTextString(m) }
func (*NftItemAllResponse) ProtoMessage()    {}
func (*NftItemAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dcc61ddcf845424a, []int{7}
}
func (m *NftItemAllResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NftItemAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NftItemAllResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NftItemAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NftItemAllResponse.Merge(m, src)
}
func (m *NftItemAllResponse) XXX_Size() int {
	return m.Size()
}
func (m *NftItemAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NftItemAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NftItemAllResponse proto.InternalMessageInfo

func (m *NftItemAllResponse) GetNftItem() []*NftItem {
	if m != nil {
		return m.NftItem
	}
	return nil
}

func (m *NftItemAllResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*NftIdListOfOwnerRequest)(nil), "firmachain.nft.NftIdListOfOwnerRequest")
	proto.RegisterType((*NftIdListOfOwnerResponse)(nil), "firmachain.nft.NftIdListOfOwnerResponse")
	proto.RegisterType((*BalanceOfRequest)(nil), "firmachain.nft.BalanceOfRequest")
	proto.RegisterType((*BalanceOfResponse)(nil), "firmachain.nft.BalanceOfResponse")
	proto.RegisterType((*NftItemRequest)(nil), "firmachain.nft.NftItemRequest")
	proto.RegisterType((*NftItemResponse)(nil), "firmachain.nft.NftItemResponse")
	proto.RegisterType((*NftItemAllRequest)(nil), "firmachain.nft.NftItemAllRequest")
	proto.RegisterType((*NftItemAllResponse)(nil), "firmachain.nft.NftItemAllResponse")
}

func init() { proto.RegisterFile("firmachain/nft/query.proto", fileDescriptor_dcc61ddcf845424a) }

var fileDescriptor_dcc61ddcf845424a = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4d, 0x6f, 0x13, 0x3d,
	0x14, 0x85, 0xeb, 0x34, 0x7d, 0xfb, 0xe6, 0x06, 0x42, 0x6b, 0x21, 0x35, 0x1a, 0xc1, 0x90, 0x0e,
	0x55, 0x93, 0x16, 0x18, 0xb7, 0xa9, 0x10, 0xeb, 0x56, 0x02, 0x04, 0x42, 0x04, 0xb2, 0x84, 0x45,
	0xe4, 0x64, 0x3c, 0xa9, 0xa5, 0x19, 0x3b, 0x8d, 0x9d, 0x42, 0x55, 0x01, 0x12, 0x48, 0xac, 0x41,
	0xec, 0x58, 0xf2, 0x6b, 0x58, 0x56, 0x62, 0xc3, 0x12, 0x25, 0xfc, 0x10, 0x94, 0x19, 0xe7, 0xb3,
	0xf9, 0x00, 0xc4, 0x2e, 0x63, 0x9f, 0x7b, 0xcf, 0x63, 0xdf, 0xe3, 0x80, 0xe5, 0xf3, 0x66, 0x48,
	0x6b, 0x87, 0x94, 0x0b, 0x22, 0x7c, 0x4d, 0x8e, 0x5a, 0xac, 0x79, 0xe2, 0x36, 0x9a, 0x52, 0x4b,
	0x9c, 0x19, 0xec, 0xb9, 0xc2, 0xd7, 0xd6, 0x95, 0xba, 0x94, 0xf5, 0x80, 0x11, 0xda, 0xe0, 0x84,
	0x0a, 0x21, 0x35, 0xd5, 0x5c, 0x0a, 0x15, 0xab, 0xad, 0xed, 0x9a, 0x54, 0xa1, 0x54, 0xa4, 0x4a,
	0x15, 0x8b, 0xdb, 0x90, 0xe3, 0xdd, 0x2a, 0xd3, 0x74, 0x97, 0x34, 0x68, 0x9d, 0x8b, 0x48, 0x6c,
	0xb4, 0x57, 0xc7, 0x5c, 0x85, 0xaf, 0x2b, 0x5c, 0xb3, 0x30, 0xde, 0x76, 0xde, 0x23, 0x58, 0x7b,
	0xec, 0xeb, 0x07, 0xde, 0x23, 0xae, 0x74, 0xc9, 0x2f, 0xbd, 0x10, 0xac, 0x59, 0x66, 0x47, 0x2d,
	0xa6, 0x34, 0xbe, 0x0e, 0x17, 0x65, 0xf7, 0xbb, 0x42, 0x3d, 0xaf, 0xc9, 0x94, 0xca, 0xa2, 0x1c,
	0x2a, 0xa4, 0xca, 0x17, 0xa2, 0xc5, 0xfd, 0x78, 0x0d, 0xdf, 0x03, 0x18, 0x78, 0x66, 0x13, 0x39,
	0x54, 0x48, 0x17, 0x37, 0xdd, 0x18, 0xd0, 0xed, 0x02, 0xba, 0xf1, 0x39, 0x0d, 0xa0, 0xfb, 0x84,
	0xd6, 0x99, 0x31, 0x28, 0x0f, 0x55, 0x3a, 0xef, 0x10, 0x64, 0xcf, 0x83, 0xa8, 0x86, 0x14, 0x8a,
	0x61, 0x1b, 0xd2, 0x11, 0xb7, 0x57, 0x09, 0xb8, 0xd2, 0x59, 0x94, 0x5b, 0x2c, 0x24, 0xcb, 0x29,
	0xd1, 0x93, 0xe3, 0xfb, 0x13, 0x20, 0xf2, 0x73, 0x21, 0xe2, 0xe6, 0x23, 0x14, 0x77, 0x60, 0xe5,
	0x80, 0x06, 0x54, 0xd4, 0x58, 0xc9, 0xff, 0x93, 0x6b, 0x70, 0xb6, 0x60, 0x75, 0xa8, 0xd0, 0x60,
	0x5f, 0x86, 0x25, 0x2d, 0x35, 0x0d, 0xa2, 0x8a, 0x64, 0x39, 0xfe, 0x70, 0x72, 0x90, 0xe9, 0x1e,
	0x54, 0xb3, 0xb0, 0xe7, 0x90, 0x81, 0x04, 0xf7, 0x8c, 0x28, 0xc1, 0x3d, 0xe7, 0x2e, 0x5c, 0xea,
	0x2b, 0x4c, 0xab, 0x22, 0xfc, 0xdf, 0x9b, 0x5c, 0x24, 0x4c, 0x17, 0xd7, 0xdc, 0xd1, 0xcc, 0xb8,
	0xbd, 0x92, 0x65, 0x11, 0xff, 0x70, 0x9e, 0xc3, 0xaa, 0x59, 0xdb, 0x0f, 0x82, 0x9e, 0xd7, 0xe8,
	0xbc, 0xd0, 0x5f, 0xcf, 0xeb, 0x23, 0x02, 0x3c, 0xdc, 0x7d, 0x22, 0xe7, 0xe2, 0xef, 0x70, 0xfe,
	0xb3, 0xe9, 0x15, 0xbf, 0x24, 0x61, 0xe9, 0x69, 0x57, 0x8a, 0x3f, 0x23, 0x58, 0x19, 0x4f, 0x13,
	0xce, 0x4f, 0x22, 0x99, 0x10, 0x7c, 0xab, 0x30, 0x5f, 0x18, 0xbb, 0x3b, 0x7b, 0x6f, 0xbf, 0xfd,
	0xfc, 0x94, 0xb8, 0x85, 0x6f, 0x90, 0xa1, 0x67, 0x76, 0xfe, 0xc5, 0x8d, 0x72, 0xbc, 0x86, 0x54,
	0x3f, 0x2b, 0x38, 0x37, 0xee, 0x35, 0x9e, 0x3f, 0x6b, 0x7d, 0x86, 0xc2, 0x60, 0xdc, 0x8c, 0x30,
	0x36, 0xf1, 0xc6, 0x0c, 0x8c, 0x6a, 0xdf, 0xf2, 0x14, 0x96, 0xcd, 0x0c, 0xb0, 0x3d, 0x6d, 0x38,
	0xc6, 0xfb, 0xda, 0xd4, 0x7d, 0xe3, 0x4c, 0x22, 0xe7, 0x2d, 0x9c, 0x9f, 0x73, 0x01, 0x9a, 0x85,
	0xe4, 0x94, 0x7b, 0xaf, 0xf0, 0x1b, 0x80, 0x41, 0x6c, 0xf0, 0xfa, 0x94, 0xfe, 0x83, 0xc0, 0x5a,
	0xce, 0x2c, 0x89, 0xa1, 0xd8, 0x8e, 0x28, 0x36, 0xb0, 0x33, 0x9f, 0xe2, 0xe0, 0xe1, 0xd7, 0xb6,
	0x8d, 0xce, 0xda, 0x36, 0xfa, 0xd1, 0xb6, 0xd1, 0x87, 0x8e, 0xbd, 0x70, 0xd6, 0xb1, 0x17, 0xbe,
	0x77, 0xec, 0x85, 0x67, 0x3b, 0x75, 0xae, 0x0f, 0x5b, 0x55, 0xb7, 0x26, 0xc3, 0x29, 0x7d, 0x8e,
	0x77, 0x6e, 0x93, 0x97, 0x51, 0x37, 0x7d, 0xd2, 0x60, 0xaa, 0xfa, 0x5f, 0xf4, 0x27, 0xba, 0xf7,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x2c, 0x69, 0x03, 0xdb, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a list of NftListOfOwner items.
	NftIdListOfOwner(ctx context.Context, in *NftIdListOfOwnerRequest, opts ...grpc.CallOption) (*NftIdListOfOwnerResponse, error)
	// Queries a list of balanceOf items.
	BalanceOf(ctx context.Context, in *BalanceOfRequest, opts ...grpc.CallOption) (*BalanceOfResponse, error)
	// Queries a nftItem by id.
	NftItem(ctx context.Context, in *NftItemRequest, opts ...grpc.CallOption) (*NftItemResponse, error)
	// Queries a list of nftItem items.
	NftItemAll(ctx context.Context, in *NftItemAllRequest, opts ...grpc.CallOption) (*NftItemAllResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) NftIdListOfOwner(ctx context.Context, in *NftIdListOfOwnerRequest, opts ...grpc.CallOption) (*NftIdListOfOwnerResponse, error) {
	out := new(NftIdListOfOwnerResponse)
	err := c.cc.Invoke(ctx, "/firmachain.nft.Query/NftIdListOfOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BalanceOf(ctx context.Context, in *BalanceOfRequest, opts ...grpc.CallOption) (*BalanceOfResponse, error) {
	out := new(BalanceOfResponse)
	err := c.cc.Invoke(ctx, "/firmachain.nft.Query/BalanceOf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NftItem(ctx context.Context, in *NftItemRequest, opts ...grpc.CallOption) (*NftItemResponse, error) {
	out := new(NftItemResponse)
	err := c.cc.Invoke(ctx, "/firmachain.nft.Query/NftItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NftItemAll(ctx context.Context, in *NftItemAllRequest, opts ...grpc.CallOption) (*NftItemAllResponse, error) {
	out := new(NftItemAllResponse)
	err := c.cc.Invoke(ctx, "/firmachain.nft.Query/NftItemAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a list of NftListOfOwner items.
	NftIdListOfOwner(context.Context, *NftIdListOfOwnerRequest) (*NftIdListOfOwnerResponse, error)
	// Queries a list of balanceOf items.
	BalanceOf(context.Context, *BalanceOfRequest) (*BalanceOfResponse, error)
	// Queries a nftItem by id.
	NftItem(context.Context, *NftItemRequest) (*NftItemResponse, error)
	// Queries a list of nftItem items.
	NftItemAll(context.Context, *NftItemAllRequest) (*NftItemAllResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) NftIdListOfOwner(ctx context.Context, req *NftIdListOfOwnerRequest) (*NftIdListOfOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NftIdListOfOwner not implemented")
}
func (*UnimplementedQueryServer) BalanceOf(ctx context.Context, req *BalanceOfRequest) (*BalanceOfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BalanceOf not implemented")
}
func (*UnimplementedQueryServer) NftItem(ctx context.Context, req *NftItemRequest) (*NftItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NftItem not implemented")
}
func (*UnimplementedQueryServer) NftItemAll(ctx context.Context, req *NftItemAllRequest) (*NftItemAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NftItemAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_NftIdListOfOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NftIdListOfOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NftIdListOfOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmachain.nft.Query/NftIdListOfOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NftIdListOfOwner(ctx, req.(*NftIdListOfOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BalanceOf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceOfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BalanceOf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmachain.nft.Query/BalanceOf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BalanceOf(ctx, req.(*BalanceOfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NftItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NftItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NftItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmachain.nft.Query/NftItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NftItem(ctx, req.(*NftItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NftItemAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NftItemAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NftItemAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/firmachain.nft.Query/NftItemAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NftItemAll(ctx, req.(*NftItemAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "firmachain.nft.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NftIdListOfOwner",
			Handler:    _Query_NftIdListOfOwner_Handler,
		},
		{
			MethodName: "BalanceOf",
			Handler:    _Query_BalanceOf_Handler,
		},
		{
			MethodName: "NftItem",
			Handler:    _Query_NftItem_Handler,
		},
		{
			MethodName: "NftItemAll",
			Handler:    _Query_NftItemAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "firmachain/nft/query.proto",
}

func (m *NftIdListOfOwnerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftIdListOfOwnerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftIdListOfOwnerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NftIdListOfOwnerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftIdListOfOwnerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftIdListOfOwnerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.NftIdList) > 0 {
		dAtA4 := make([]byte, len(m.NftIdList)*10)
		var j3 int
		for _, num := range m.NftIdList {
			for num >= 1<<7 {
				dAtA4[j3] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j3++
			}
			dAtA4[j3] = uint8(num)
			j3++
		}
		i -= j3
		copy(dAtA[i:], dAtA4[:j3])
		i = encodeVarintQuery(dAtA, i, uint64(j3))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BalanceOfRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BalanceOfRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BalanceOfRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *BalanceOfResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BalanceOfResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BalanceOfResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Total != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Total))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NftItemRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftItemRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftItemRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NftItemResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftItemResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftItemResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NftItem != nil {
		{
			size, err := m.NftItem.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NftItemAllRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftItemAllRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftItemAllRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *NftItemAllResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NftItemAllResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NftItemAllResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.NftItem) > 0 {
		for iNdEx := len(m.NftItem) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NftItem[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NftIdListOfOwnerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *NftIdListOfOwnerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NftIdList) > 0 {
		l = 0
		for _, e := range m.NftIdList {
			l += sovQuery(uint64(e))
		}
		n += 1 + sovQuery(uint64(l)) + l
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *BalanceOfRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *BalanceOfResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Total != 0 {
		n += 1 + sovQuery(uint64(m.Total))
	}
	return n
}

func (m *NftItemRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *NftItemResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NftItem != nil {
		l = m.NftItem.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *NftItemAllRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *NftItemAllResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.NftItem) > 0 {
		for _, e := range m.NftItem {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NftIdListOfOwnerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftIdListOfOwnerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftIdListOfOwnerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NftIdListOfOwnerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftIdListOfOwnerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftIdListOfOwnerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.NftIdList = append(m.NftIdList, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowQuery
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthQuery
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthQuery
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.NftIdList) == 0 {
					m.NftIdList = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowQuery
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.NftIdList = append(m.NftIdList, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field NftIdList", wireType)
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BalanceOfRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BalanceOfRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BalanceOfRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BalanceOfResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BalanceOfResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BalanceOfResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			m.Total = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Total |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NftItemRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftItemRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftItemRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NftItemResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftItemResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftItemResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftItem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.NftItem == nil {
				m.NftItem = &NftItem{}
			}
			if err := m.NftItem.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NftItemAllRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftItemAllRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftItemAllRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NftItemAllResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NftItemAllResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NftItemAllResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NftItem", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NftItem = append(m.NftItem, &NftItem{})
			if err := m.NftItem[len(m.NftItem)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
