accounts:
  - name: alice
    coins: ["2000000000ufct", "200000000stake"]
    mnemonic: ozone unfold device pave lemon potato omit insect column wise cover hint narrow large provide kidney episode clay notable milk mention dizzy muffin crazy
  - name: bob1
    coins: ["1000000000ufct", "100000000stake"]
    mnemonic: burst torch enemy quick crime slogan trust wood hamster way armor visual common language close park leg ill ball board couch nose theory must
  - name: bob2
    coins: ["1000000000ufct", "100000000stake"]
  - name: bob3
    coins: ["1000000000ufct", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob1
  coins: ["5ufct", "100000stake"]
build:
  binary: "firmachaind"

init:
  app:
    minimum-gas-prices: "0.01ufct"