// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: firmachain/contract/contract_file.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Contract file representation
type ContractFile struct {
	Creator            string   `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	FileHash           string   `protobuf:"bytes,2,opt,name=fileHash,proto3" json:"fileHash,omitempty"`
	TimeStamp          uint64   `protobuf:"varint,3,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	OwnerList          []string `protobuf:"bytes,4,rep,name=ownerList,proto3" json:"ownerList,omitempty"`
	MetaDataJsonString string   `protobuf:"bytes,5,opt,name=metaDataJsonString,proto3" json:"metaDataJsonString,omitempty"`
}

func (m *ContractFile) Reset()         { *m = ContractFile{} }
func (m *ContractFile) String() string { return proto.CompactTextString(m) }
func (*ContractFile) ProtoMessage()    {}
func (*ContractFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb8c49aee3216b5, []int{0}
}
func (m *ContractFile) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ContractFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ContractFile.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ContractFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractFile.Merge(m, src)
}
func (m *ContractFile) XXX_Size() int {
	return m.Size()
}
func (m *ContractFile) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractFile.DiscardUnknown(m)
}

var xxx_messageInfo_ContractFile proto.InternalMessageInfo

func (m *ContractFile) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ContractFile) GetFileHash() string {
	if m != nil {
		return m.FileHash
	}
	return ""
}

func (m *ContractFile) GetTimeStamp() uint64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *ContractFile) GetOwnerList() []string {
	if m != nil {
		return m.OwnerList
	}
	return nil
}

func (m *ContractFile) GetMetaDataJsonString() string {
	if m != nil {
		return m.MetaDataJsonString
	}
	return ""
}

func init() {
	proto.RegisterType((*ContractFile)(nil), "firmachain.contract.ContractFile")
}

func init() {
	proto.RegisterFile("firmachain/contract/contract_file.proto", fileDescriptor_bdb8c49aee3216b5)
}

var fileDescriptor_bdb8c49aee3216b5 = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0xcb, 0x2c, 0xca,
	0x4d, 0x4c, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0x4a, 0x4c, 0x2e, 0x81,
	0x33, 0xe2, 0xd3, 0x32, 0x73, 0x52, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84, 0x11, 0x0a,
	0xf5, 0x60, 0xf2, 0x4a, 0x1b, 0x18, 0xb9, 0x78, 0x9c, 0xa1, 0x1c, 0xb7, 0xcc, 0x9c, 0x54, 0x21,
	0x09, 0x2e, 0xf6, 0xe4, 0xa2, 0xd4, 0xc4, 0x92, 0xfc, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x18, 0x57, 0x48, 0x8a, 0x8b, 0x03, 0x64, 0x9a, 0x47, 0x62, 0x71, 0x86, 0x04, 0x13, 0x58,
	0x0a, 0xce, 0x17, 0x92, 0xe1, 0xe2, 0x2c, 0xc9, 0xcc, 0x4d, 0x0d, 0x2e, 0x49, 0xcc, 0x2d, 0x90,
	0x60, 0x56, 0x60, 0xd4, 0x60, 0x09, 0x42, 0x08, 0x80, 0x64, 0xf3, 0xcb, 0xf3, 0x52, 0x8b, 0x7c,
	0x32, 0x8b, 0x4b, 0x24, 0x58, 0x14, 0x98, 0x35, 0x38, 0x83, 0x10, 0x02, 0x42, 0x7a, 0x5c, 0x42,
	0xb9, 0xa9, 0x25, 0x89, 0x2e, 0x89, 0x25, 0x89, 0x5e, 0xc5, 0xf9, 0x79, 0xc1, 0x25, 0x45, 0x99,
	0x79, 0xe9, 0x12, 0xac, 0x60, 0x1b, 0xb0, 0xc8, 0x38, 0xf9, 0x9f, 0x78, 0x24, 0xc7, 0x78, 0xe1,
	0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70,
	0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x69, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae,
	0x3e, 0x52, 0xa8, 0x20, 0x31, 0xcb, 0x0c, 0x4c, 0xf5, 0x2b, 0x10, 0xc1, 0x54, 0x52, 0x59, 0x90,
	0x5a, 0x9c, 0xc4, 0x06, 0x0e, 0x1f, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x34, 0x14,
	0x0b, 0x4a, 0x01, 0x00, 0x00,
}

func (m *ContractFile) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ContractFile) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ContractFile) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MetaDataJsonString) > 0 {
		i -= len(m.MetaDataJsonString)
		copy(dAtA[i:], m.MetaDataJsonString)
		i = encodeVarintContractFile(dAtA, i, uint64(len(m.MetaDataJsonString)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OwnerList) > 0 {
		for iNdEx := len(m.OwnerList) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.OwnerList[iNdEx])
			copy(dAtA[i:], m.OwnerList[iNdEx])
			i = encodeVarintContractFile(dAtA, i, uint64(len(m.OwnerList[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.TimeStamp != 0 {
		i = encodeVarintContractFile(dAtA, i, uint64(m.TimeStamp))
		i--
		dAtA[i] = 0x18
	}
	if len(m.FileHash) > 0 {
		i -= len(m.FileHash)
		copy(dAtA[i:], m.FileHash)
		i = encodeVarintContractFile(dAtA, i, uint64(len(m.FileHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintContractFile(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintContractFile(dAtA []byte, offset int, v uint64) int {
	offset -= sovContractFile(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ContractFile) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovContractFile(uint64(l))
	}
	l = len(m.FileHash)
	if l > 0 {
		n += 1 + l + sovContractFile(uint64(l))
	}
	if m.TimeStamp != 0 {
		n += 1 + sovContractFile(uint64(m.TimeStamp))
	}
	if len(m.OwnerList) > 0 {
		for _, s := range m.OwnerList {
			l = len(s)
			n += 1 + l + sovContractFile(uint64(l))
		}
	}
	l = len(m.MetaDataJsonString)
	if l > 0 {
		n += 1 + l + sovContractFile(uint64(l))
	}
	return n
}

func sovContractFile(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozContractFile(x uint64) (n int) {
	return sovContractFile(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ContractFile) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContractFile
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ContractFile: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ContractFile: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContractFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContractFile
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContractFile
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FileHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContractFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContractFile
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContractFile
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FileHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeStamp", wireType)
			}
			m.TimeStamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContractFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeStamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerList", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContractFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContractFile
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContractFile
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerList = append(m.OwnerList, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetaDataJsonString", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContractFile
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthContractFile
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthContractFile
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetaDataJsonString = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContractFile(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContractFile
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContractFile(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContractFile
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContractFile
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContractFile
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthContractFile
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupContractFile
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthContractFile
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthContractFile        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContractFile          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupContractFile = fmt.Errorf("proto: unexpected end of group")
)
